<?php
/**
 * 错误码
 */
class ErrorCode {
    //正确
    CONST NO_ERROR = 20000;
    
    //默认错误
    CONST DEFAULT_ERROR = 40000;
    
    //客户端参数错误
    CONST ERROR_CLIENT_PARAMS_ERROR = 40001;
    CONST ERROR_CLIENT_VERIFY_CODE_ERROR = 40002;
    
    //用户未登录
    CONST ERROR_USER_NOT_LOGIN = 50001;
    //用户名或密码错误
    CONST ERROR_USER_NAME_OR_PASSWORD = 50002;
    CONST ERROR_USER_ALREADY_LOGIN = 50003;//用户已经登录
    CONST ERROR_USER_NOT_REAL_AUTH = 50004;//用户未实名认证
    CONST ERROR_USER_NOT_COMPLETE_BASE_INFO = 50005;//用户未填写基础信息
    CONST ERROR_USER_IS_LAWYER = 50006;//用户未填写基础信息
    
    //通用错误返回
    CONST ERROR_NO_AUTH = 51001;
    CONST ERROR_COMMON_FAILED = 51002;
    CONST ERROR_BAD_VERIFY_CODE = 51003;
    CONST ERROR_USER_EXIST = 51004;
    
    CONST ERROR_VERIFY_CODE_RESET = 510006;
    CONST ERROR_VERIFY_CODE_ACTIVE = 510007;
    
    CONST ERROR_USER_NO_EXIST = 51008;
    
    //业务处理流程上的依赖数据错误 - 一般是客户端传入的数据不对
    CONST EXCEPTION_BAD_DEPENDENTS = 60001;
    CONST EXCEPTION_OVERFLOW = 60002;
}